spring.application.name=coffee-shop-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/coffee_shop
spring.datasource.username=coffee_shop
spring.datasource.password=coffee_shop

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info